version: "1.0"
name: "plusbusy-backend"
services:
  db:
    image: postgres:14.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
  db-admin:
    image: dpage/pgadmin4
    hostname: pgadmin
    domainname: pgadmin.com
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - '8080:80'
    links:
      - "db:database"
